import React from 'react';

export default function 4BedroomDuplexApartmentSection__structures10() {
    return (
        <React.Fragment>
            <>
                <div>  {/* Blog Article */}  <div className="max-w-3xl px-4 pt-6 lg:pt-10 pb-12 sm:px-6 lg:px-8 mx-auto">    <div className="max-w-2xl">      {/* Avatar Media */}      <div className="flex justify-between items-center mb-6">        <div className="flex w-full sm:items-center gap-x-5 sm:gap-x-3">          <div className="grow" />      </div>    </div>      {/* End Avatar Media */}      {/* Content */}      <div className="space-y-5 md:space-y-8">        <div className="space-y-3">          <h2 className="text-2xl font-bold md:text-3xl">Construction of a 4 bedroom semi detached duplex at barrack busstop, Soluyi, Gbagada, Lagos state.</h2>      </div>        <p className="text-lg text-gray-800" contentEditable="false">In&nbsp;The bustling neighborhood of Soluyi in Gbagada, Lagos State, is set to welcome an exciting new residential development. Construction has begun on two units of 4 bedroom semi-detached duplexes at Barrack Bus Stop, promising to bring modern, spacious living to this vibrant area.</p>        <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-31.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">Construction of 8 units of 4 bedrooms semi detached duplex at Engr. Lere Adigun GRA Estate, Bashorun Ibadan.</figcaption>      </figure>        <p className="text-lg text-gray-800" contentEditable="false">These semi-detached duplexes are designed to cater to the growing demand for high-quality family homes in Lagos. Each unit will feature four bedrooms, providing ample space for comfortable family living or for those who desire extra rooms for a home office or guest accommodation.</p>        <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-32.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">2 bedroom on ground floor of front apartment and 4 bedroom duplex on back apartment plus parking space for both apartment on a 300sqm land.</figcaption>      </figure>        <div className="space-y-3" />        <ul className="list-disc list-outside space-y-5 ps-5 text-lg text-gray-800" />        <p className="text-lg text-gray-800" contentEditable="true">This development is expected to attract professionals, growing families, and investors looking for properties in up-and-coming neighborhoods. The semi-detached design offers a sense of privacy while still fostering a community feel.
          As construction progresses, potential buyers and curious onlookers can witness the transformation of this plot into two stunning homes. The project showcases the ongoing development and urbanization of Lagos, particularly in sought-after areas like Gbagada.
          For those interested in learning more about these properties or tracking the construction progress, it's recommended to contact local real estate agents or the project developers directly.</p>        <div>
          <a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Architecture</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Innovate</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Design</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Development</a>
        </div>    </div>      {/* End Content */}  </div></div>  {/* End Blog Article */}  {/* Sticky Share Group */}  {/* End Sticky Share Group */}
</div>


            </>
        </React.Fragment>
    );
}

