import React from 'react';

export default function 8UnitsSemiDetachedAtIbadanLereAdigunSection__structures10() {
    return (
        <React.Fragment>
            <>
                <div>  {/* Blog Article */}  <div className="max-w-3xl px-4 pt-6 lg:pt-10 pb-12 sm:px-6 lg:px-8 mx-auto">    <div className="max-w-2xl">      {/* Avatar Media */}      <div className="flex justify-between items-center mb-6">        <div className="flex w-full sm:items-center gap-x-5 sm:gap-x-3" />    </div>      {/* End Avatar Media */}      {/* Content */}      <div className="space-y-5 md:space-y-8">        <div className="space-y-3">          <h2 className="text-2xl font-bold md:text-3xl">Construction of a 8 unit bedroom on ground floor of front apartment and 4 bedroom duplex...</h2>      </div>        <p className="text-lg text-gray-800">A significant new residential project has broken ground, promising to bring 8 units of luxurious 4-bedroom semi-detached duplexes to this coveted area. in Ibadan lere adigun GRA</p>        <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-1.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">Construction of 8 units of 4 bedrooms semi detached duplex at Engr. Lere Adigun GRA Estate, Bashorun Ibadan.</figcaption>      </figure>        <p className="text-lg text-gray-800">This ambitious project is set to transform the local real estate landscape, offering modern, spacious living in one of Ibadan's most sought-after neighborhoods. The development caters to the growing demand for high-quality family homes in Oyo State's capital city.</p>                <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-4.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">2 bedroom on ground floor of front apartment and 4 bedroom duplex on back apartment plus parking space for both apartment on a 300sqm land.</figcaption>      </figure>        <div className="space-y-3">                    <p className="text-lg text-gray-800">The construction of these 8 units reflects the growing sophistication of Ibadan's real estate market and the increasing demand for luxury properties in well-planned estates. It's a clear indication of the city's economic growth and the rising standards of living in Oyo State.
            As the project progresses, it will be exciting to watch these duplexes take shape, transforming the landscape of Engr. Lere Adigun GRA Estate. The development promises to set a new standard for residential properties in Ibadan, potentially influencing future projects in the area.</p>      </div>        <ul className="list-disc list-outside space-y-5 ps-5 text-lg text-gray-800">                </ul>                <div>
          <a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Architecture</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Innovate</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Free</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Development</a>
        </div>    </div>      {/* End Content */}  </div></div>  {/* End Blog Article */}  {/* Sticky Share Group */}  {/* End Sticky Share Group */}
</div>


            </>
        </React.Fragment>
    );
}

