import React from 'react';

export default function LoginSection__structures1() {
    return (
        <React.Fragment>
            <>
                <div>  <main className="w-full h-screen flex flex-col items-center justify-center px-4">    <div className="max-w-sm w-full text-gray-600 space-y-5">      <div className="text-center pb-8">        <div className="mt-5">          <div>            <a href="/" className="mb-6 text-2xl font-semibold text-gray-900 flex justify-center">              <div>                <img className="w-auto h-8 mr-2" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/logo.png" alt="logo" />            </div>              ARSHCON          </a>        </div>          <h3 className="text-2xl font-bold sm:text-3xl">Log in to your account</h3>      </div>    </div>      <form onsubmit="event.preventDefault()" className="space-y-5">        <div>          <label className="font-medium">Email</label>          <input type="email" required className="w-full mt-2 px-3 py-2 text-gray-500 bg-transparent outline-none border focus:border-indigo-600 shadow-sm rounded-lg" />      </div>        <div>          <label className="font-medium">Password</label>          <input type="password" required className="w-full mt-2 px-3 py-2 text-gray-500 bg-transparent outline-none border focus:border-indigo-600 shadow-sm rounded-lg" />      </div>        <div className="flex items-center justify-between text-sm">          <div className="flex items-center gap-x-3">            <input type="checkbox" id="remember-me-checkbox" className="checkbox-item peer hidden" />            <label htmlFor="remember-me-checkbox" className="relative flex w-5 h-5 bg-white peer-checked:bg-indigo-600 rounded-md border ring-offset-2 ring-indigo-600 duration-150 peer-active:ring cursor-pointer after:absolute after:inset-x-0 after:top-[3px] after:m-auto after:w-1.5 after:h-2.5 after:border-r-2 after:border-b-2 after:border-white after:rotate-45" />            <span>Remember me</span>        </div>          <a href="javascript:void(0)" className="text-center text-red-600 hover:text-red-500">Forgot password?</a>      </div>        <button className="w-full px-4 py-2 text-white font-medium rounded-lg duration-150 bg-red-600 active:bg-red-600 hover:bg-red-500">Sign in</button>    </form>      <button className="w-full flex items-center justify-center gap-x-3 py-2.5 border rounded-lg text-sm font-medium duration-150 bg-white">        {/* SVG for Google Sign In */}        <img src="https://raw.githubusercontent.com/sidiDev/remote-assets/7cd06bf1d8859c578c2efbfda2c68bd6bedc66d8/google-icon.svg" alt="Google" className="w-5 h-5" />        {/* Comment: Google Icon SVG here */}        Continue with Google    </button>      <p className="text-center">Don't have an account? <a href="javascript:void(0)" className="font-medium text-red-600 hover:text-red-500">Sign up</a></p>  </div></main></div>


            </>
        </React.Fragment>
    );
}

