import React from 'react';

export default function SemiDetachedDuplexPeaceEstateSection__structures12() {
    return (
        <React.Fragment>
            <>
                <div className="mx-auto px-20 border-b py-6">  <ol className="border-s border-neutral-300 dark:border-neutral-500 md:flex md:justify-center md:gap-6 md:border-s-0 md:border-t">    {/*First item*/}    <li>      <div className="flex-start flex items-center pt-2 md:block md:pt-0">        <div className="-ms-[5px] me-3 h-[9px] w-[9px] rounded-full bg-neutral-300 dark:bg-neutral-500 md:-mt-[5px] md:me-0 md:ms-0" />    </div>      <div className="ms-4 mt-2 pb-5 md:ms-0">        <h4 className="mb-1.5 text-xl font-semibold">Project Overview:</h4>        <p className="mb-1.5 text-neutral-500">Address:&nbsp;Peace Estate, Soluyi, Gbagada, Lagos state.</p>        <p className="mb-1.5 text-neutral-500">Property Type: Semi-detached duplex</p>        <p className="mb-1.5 text-neutral-500">Number of Units: 2</p>        <p className="mb-1.5 text-neutral-500">Bedrooms: 4 per unit</p>        <p className="mb-1.5 text-neutral-500">Status: Under construction</p>    </div>  </li>    {/*Second item*/}    <li>      <div className="flex-start flex items-center pt-2 md:block md:pt-0">        <div className="-ms-[5px] me-3 h-[9px] w-[9px] rounded-full bg-neutral-300 dark:bg-neutral-500 md:-mt-[5px] md:me-0 md:ms-0" />    </div>      <div className="ms-4 mt-2 pb-5 md:ms-0">        <h4 className="mb-1.5 text-xl font-semibold">Key Features:</h4>        <p className="mb-1.5 text-neutral-500">Modern architectural design</p>        <p className="mb-1.5 text-neutral-500">Spacious living areas</p>        <p className="mb-1.5 text-neutral-500">Well-appointed kitchens</p>        <p className="mb-1.5 text-neutral-500">Multiple bathrooms</p>        <p className="mb-1.5 text-neutral-500">High-quality finishes and fixtures</p>        <p className="mb-1.5 text-neutral-500">Security features</p>        <h4 className="mb-1.5 text-xl font-semibold" style={{-twBorderOpacity: 1, -twShadow: '0 0 #0000', -twRingInset: '', -twRingOffsetWidth: 0, -twRingOffsetColor: '#fff', -twRingColor: 'rgb(59 130 246 / 0.5)', -twRingOffsetShadow: '0 0 #0000', -twRingShadow: '0 0 #0000', -twBorderSpacingX: 0, -twBorderSpacingY: 0, -twTranslateX: 0, -twTranslateY: 0, -twRotate: 0, -twSkewX: 0, -twSkewY: 0, -twScaleX: 1, -twScaleY: 1, -twPanX: '', -twPanY: '', -twPinchZoom: '', -twScrollSnapStrictness: 'proximity', -twGradientFromPosition: '', -twGradientViaPosition: '', -twGradientToPosition: '', -twOrdinal: '', -twSlashedZero: '', -twNumericFigure: '', -twNumericSpacing: '', -twNumericFraction: '', -twShadowColored: '0 0 #0000', -twBlur: '', -twBrightness: '', -twContrast: '', -twGrayscale: '', -twHueRotate: '', -twInvert: '', -twSaturate: '', -twSepia: '', -twDropShadow: '', -twBackdropBlur: '', -twBackdropBrightness: '', -twBackdropContrast: '', -twBackdropGrayscale: '', -twBackdropHueRotate: '', -twBackdropInvert: '', -twBackdropOpacity: '', -twBackdropSaturate: '', -twBackdropSepia: '', outline: 'none', userSelect: 'text'}} />    </div>  </li></ol>
</div>


            </>
        </React.Fragment>
    );
}

