import React from 'react';

export default function SemiDetachedDuplexPeaceEstateSection__structures10() {
    return (
        <React.Fragment>
            <>
                <div>  {/* Blog Article */}  <div className="max-w-3xl px-4 pt-6 lg:pt-10 pb-12 sm:px-6 lg:px-8 mx-auto">    <div className="max-w-2xl">      {/* Avatar Media */}      <div className="flex justify-between items-center mb-6">        <div className="flex w-full sm:items-center gap-x-5 sm:gap-x-3">          <div className="grow" />      </div>    </div>      {/* End Avatar Media */}      {/* Content */}      <div className="space-y-5 md:space-y-8">        <div className="space-y-3">          <h2 className="text-2xl font-bold md:text-3xl">Construction of a semi-detached duplex @peace estate</h2>      </div>        <p className="text-lg text-gray-800">Construction begins on a stunning new semi-detached duplex in Peace Estate, Soluyi, Gbagada, Lagos state.. This project promises to bring modern, spacious living to one of Lagos State's most sought-after neighborhoods. Duplex comprise of 2 unit of 4 bedroom duplex on half plots of land.</p>        <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-23.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">Construction of 8 units of 4 bedrooms semi detached duplex at Engr. Lere Adigun GRA Estate, Bashorun Ibadan.</figcaption>      </figure>        <p className="text-lg text-gray-800">As we've grown, we've seen how Preline has helped companies such as Spotify, Microsoft, Airbnb, Facebook, and Intercom bring their designers closer together to create amazing things. We've also learned that when the culture of sharing is brought in earlier, the better teams adapt and communicate with one another.</p>                <figure>          <img className="w-full object-cover rounded-xl" src="https://static.shuffle.dev/uploads/files/3b/3bd7a8feac6edf952a72f7ffe12d973401d1bac7/project-26.jpg" alt="Image Description" />          <figcaption className="mt-3 text-sm text-center text-gray-500 dark:text-neutral-500">2 bedroom on ground floor of front apartment and 4 bedroom duplex on back apartment plus parking space for both apartment on a 300sqm land.</figcaption>      </figure>        <div className="space-y-3">          <h3 className="text-2xl font-semibold dark:text-white">Bringing the culture of sharing to everyone</h3>          <p className="text-lg text-gray-800">We know the power of sharing is real, and we want to create an opportunity for everyone to try Preline and explore how transformative open communication can be. Now you can have a team of one or two designers and unlimited spectators (think PMs, management, marketing, etc.) share work and explore the design process earlier.</p>      </div>        <ul className="list-disc list-outside space-y-5 ps-5 text-lg text-gray-800">                </ul>                <div>
          <a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Architecture</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Innovate</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Free</a><a className="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200" href="#">Development</a>
        </div>    </div>      {/* End Content */}  </div></div>  {/* End Blog Article */}  {/* Sticky Share Group */}  {/* End Sticky Share Group */}
</div>


            </>
        </React.Fragment>
    );
}

